### ISSUE TITLE
how to reproduce the figure 5?

### ISSUE THREAD

**Issue by WangHexie** [JinheonBaek/GMT#15]
![image](https://user-images.githubusercontent.com/31768052/125418278-b40d3f53-5243-4324-aae2-f8068b4e59b1.png)

**Comment by JinheonBaek** [comment]
Hello,
Thanks for your interest.

We produce the above reconstruction result of synthetic graphs (Figure 5) using the code in https://github.com/FilippoMB/Spectral-Clustering-with-Graph-Neural-Networks-for-Graph-Pooling/blob/master/Autoencoder.py as the basic building block.

If you want to get the code file that is written in Python and PyTorch, then please let me know your email address. Due to the reason that the synthetic graph reconstruction code is not well fitted into our full hierarchy of entire codes, we have not incorporated it.

Sincerely,
Jinheon Baek

**Comment by WangHexie** [comment]
@JinheonBaek Thanks for your quick reply. It would be nice to have the code file. I've sent an email to your `kaist.ac.kr` email address.

**Comment by WangHexie** [comment]
Thanks a lot.

**Comment by imSeaton** [comment]
Hi, I'm interested in the area of graph pooling, and I‘m trying to do some minor improvements based on the solid work. Could you please send the code of reconstruction of synthetic graphs written in Pytorch to my email **seatonsu@foxmail.com**   . I'll appreciate it very much.

**Comment by JinheonBaek** [comment]
@imSeaton Hi, I sent it to your email.

**Comment by imSeaton** [comment]
> @imSeaton Hi, I sent it to your email.

Thank you!
